services:
  reservation:
    image: mysql:8.0
    container_name: reservation-service
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: reservation_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

