apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack alert
    editable: true
    receivers:
      - uid: slack-uid
        type: slack
        settings:
          url: https://hooks.slack.com/services/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
        disableResolveMessage: false