server:
  port: 19094

spring:
  application:
    name: flight-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://flight-db:5432/flight_db
    username: ${FLIGHT_DB_ID}
    password: ${FLIGHT_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jdbc:
        time_zone: UTC
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: flight-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        allow.auto.create.topics: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


amadeus:
  base-url: https://test.api.amadeus.com
  client-id: ${AMADEUS_CLIENT_ID}
  client-secret: ${AMADEUS_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace