# 전체 시나리오
# 회원가입 → 로그인 → 특가 항공권 예매 요청 → 예약 대기열 서비스: 좌석 선점 처리 → 예약 대기열 서비스: 좌석 선점 성공 →
# 예약 대기열 서비스 Kafka prodcuer: 예약 선점 성공 이벤트 발행 → 예약 서비스 Kafka Consumer: 예약 임시 생성 →
# 예약 서비스: 예약 확정 (탑승객 정보 입력 + 결제 처리)




### 유저 생성 - internal
POST http://localhost:19091/api/v1/users/signup
Content-Type: application/json

{
  "username": "tester",
  "password": "12345678a*",
  "nickname": "테스터",
  "email": "test@test.com",
  "contact": "010-1111-2222"
}


### 로그인
POST http://localhost:19091/api/v1/users/login
Content-Type: application/json

{
  "username": "tester",
  "password": "12345678a*"
}
> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"))
%}

### 항공편 조회 및 저장
POST http://localhost:19091/api/v1/amadeus/flights/fetch-and-save?departureAirportCode=LGW&arrivalAirportCode=KWE&departureDate=2025-04-25T19:45:25&requiredSeats=2
Authorization: Bearer {{access_token}}


### 특가 항공권 예매 요청
POST http://localhost:19091/api/v1/queue
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "flightId" : "66b08c46-8393-480a-a8bc-3d72dcda80dd",
  "seatCount" : 2
}


### 예약 대기열 서비스 Kafka prodcuer: 예약 선점 성공 이벤트 발행

### 예약 서비스 Kafka Consumer: 예약 임시 생성




### 예약 확정 V2
PUT http://localhost:19091/api/v1/reservations/confirm
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "flightId": "57944490-33fb-4bb1-9254-1eae30a1a25c",
  "passengers": [
    {
      "name": "홍길동1",
      "birth": "1990-01-01",
      "gender": "MALE",
      "passportNumber": "P12345678"
    },
    {
      "name": "홍길동",
      "birth": "1995-06-10",
      "gender": "FEMALE",
      "passportNumber": "P87654321"
    }
  ]
}


### 예약 확정 V2, 결제 재시도
PUT http://localhost:19091/api/v1/reservations/confirm
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "flightId": "57944490-33fb-4bb1-9254-1eae30a1a25c"
}




### 예약 단일 조회
GET http://localhost:19091/api/v1/reservations/9b7f421f-47b0-47f5-aa5c-8f489697a57d
Content-Type: application/json
Authorization: Bearer {{access_token}}


## 예약 목록 조회
### 예약 목록 조회 - Default
GET http://localhost:19091/api/v1/reservations
Content-Type: application/json
Authorization: Bearer {{access_token}}
