spring:
  application:
    name: queue-service

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      host: queue-redis
      port: 6381
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 100
          max-idle: 50
          min-idle: 10
          max-wait: 1000ms

server:
  port: 19096

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/
    register-with-eureka: true