server:
  port: 19091  # 게이트웨이 서비스가 실행될 포트 번호

spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: gateway-service  # 애플리케이션 이름을 'gateway-service'로 설정
  cloud:
    gateway:
      routes: # Spring Cloud Gateway의 라우팅 설정
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/api/v1/airlines/**, /api/v1/airports/**, /api/v1/flights/**, /api/v1/amadeus/**
        # amadeus의 경우에는 internal로 추정
        - id: queue-service
          uri: lb://queue-service
          predicates:
            - Path=/api/v1/queue/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정

  kafka:
    bootstrap-servers: kafka:29092

  data:
    redis:
      host: redis
      port: 6379
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 100
          max-idle: 50
          min-idle: 10
          max-wait: 1000ms

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/  # Eureka 서버의 URL을 지정



tokenVersion-expiration: 31 # Access token 만료 기간보다 1분 길게 만일 refresh 토큰이 추가되면 또 바뀔 예정

jwt:
  secret: ${JWT_SECRET_KEY}