server:
  port: 19093

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://payments-db:3306/payments_db
    username: ${PAYMENT_DB_USERNAME}
    password: ${PAYMENT_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/
    register-with-eureka: true

import:
  api:
    key: ${IMPORT_API_KEY}
    secret:
      key: ${IMPORT_API_SECRET_KEY}