server:
  port: 19093

spring:
  profiles:
    active: local
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/payments_db
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-server:19090/eureka/
#    register-with-eureka: true
#    fetch-registry: true

import:
  api:
    key: 3514258731134757
    secret:
      key: aMGNaO99W6ivPE2tRodLfRWwBWdR2gG5FPifcZ46kUYe13GXLqSfnEcXkbl8LBNIY9z94CrmKKpSrwP9