server:
  port: 19093

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        allow.auto.create.topics: true

#  datasource:
#    url: jdbc:mysql://payments-db:3306/payments_db
#    username: ${PAYMENT_DB_USERNAME}
#    password: ${PAYMENT_DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://payments-db:5432/payments_db
    username: ${PAYMENT_DB_USERNAME}
    password: ${PAYMENT_DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

import:
  api:
    key: ${IMPORT_API_KEY}
    secret:
      key: ${IMPORT_API_SECRET_KEY}