### 유저 생성 - internal
# todo: 중복 유저 관련해서는 500에러가 나온다 수정 필요
POST http://localhost:19091/api/v1/users/signup
Content-Type: application/json

{
  "username": "tester",
  "password": "12345678a*",
  "nickname": "테스터",
  "email": "test@test.com",
  "contact": "010-1111-2222"
}

### 로그인
POST http://localhost:19091/api/v1/users/login
Content-Type: application/json

{
  "username": "tester",
  "password": "12345678a*"
}

### 유저 조회(개인)
GET http://localhost:19091/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIiLCJyb2xlIjoiQ1VTVE9NRVIiLCJ0b2tlblZlcnNpb24iOjEsImlkIjoiYjNlNDg0OWYtNjllOC00MzU0LWIxNjYtNTUyZTA1ZWM4MWEzIiwiaXNzIjoib25ldWwtdGFuZGEiLCJpYXQiOjE3NDUyMDQxMDcsImV4cCI6MTc0NTIwNTkwN30.9fZp38aeYgZcXvW8BqKA30Nx40Al__M6jw6gsg3Ermo

### 유저 정보 수정
PUT http://localhost:19091/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIiLCJyb2xlIjoiQ1VTVE9NRVIiLCJ0b2tlblZlcnNpb24iOjEsImlkIjoiYjNlNDg0OWYtNjllOC00MzU0LWIxNjYtNTUyZTA1ZWM4MWEzIiwiaXNzIjoib25ldWwtdGFuZGEiLCJpYXQiOjE3NDUyMDQxMDcsImV4cCI6MTc0NTIwNTkwN30.9fZp38aeYgZcXvW8BqKA30Nx40Al__M6jw6gsg3Ermo

{
  "nickname": "테스터",
  "email": "test@test.com",
  "contact": "010-1111-2212"
}

### 유저 암호 수정
PUT http://localhost:19091/api/v1/users/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIiLCJyb2xlIjoiQ1VTVE9NRVIiLCJ0b2tlblZlcnNpb24iOjEsImlkIjoiYjNlNDg0OWYtNjllOC00MzU0LWIxNjYtNTUyZTA1ZWM4MWEzIiwiaXNzIjoib25ldWwtdGFuZGEiLCJpYXQiOjE3NDUyMDQxMDcsImV4cCI6MTc0NTIwNTkwN30.9fZp38aeYgZcXvW8BqKA30Nx40Al__M6jw6gsg3Ermo

{
  "currentPassword": "12345678a*",
  "newPassword": "12345678a"
}

### 유저 탈퇴 todo: 추후 feignclient grpc를 통해 수정 작업 진행
DELETE http://localhost:19091/api/v1/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpZCI6ImFhZGFlYjFlLTdhNmUtNDVjZC1hZTgzLWU1YjY2NTBjZWYyNCIsInRva2VuVmVyc2lvbiI6MSwiaXNzIjoib25ldWwtdGFuZGEiLCJpYXQiOjE3NDQ5NzA4MDQsImV4cCI6MTc0NDk3MjYwNH0.Ox4FPo5JST6nGttFVkklweWUE3NddZen6YHKAl_Z_Ao

{
  "password": "12345678a"
}

### 유저 조회 username기반
GET http://localhost:19091/api/v1/users/admin/tester
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpZCI6ImFhZGFlYjFlLTdhNmUtNDVjZC1hZTgzLWU1YjY2NTBjZWYyNCIsInRva2VuVmVyc2lvbiI6MSwiaXNzIjoib25ldWwtdGFuZGEiLCJpYXQiOjE3NDQ5NzA4MDQsImV4cCI6MTc0NDk3MjYwNH0.Ox4FPo5JST6nGttFVkklweWUE3NddZen6YHKAl_Z_Ao

### 유저 권한 상승 username기반
PUT http://localhost:19091/api/v1/users/admin/tester
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpZCI6ImFhZGFlYjFlLTdhNmUtNDVjZC1hZTgzLWU1YjY2NTBjZWYyNCIsInRva2VuVmVyc2lvbiI6MSwiaXNzIjoib25ldWwtdGFuZGEiLCJpYXQiOjE3NDQ5NzA4MDQsImV4cCI6MTc0NDk3MjYwNH0.Ox4FPo5JST6nGttFVkklweWUE3NddZen6YHKAl_Z_Ao

{
  "role": "MANAGER"
}

### 유저 조회 userId기반
GET http://localhost:19091/api/v1/users/43392dc4-3848-426d-bdfa-99946b3bedbb
Content-Type: application/json


