### 유저 생성 - internal
# todo: 중복 유저 관련해서는 500에러가 나온다 수정 필요
POST http://localhost:19091/api/v1/users/signup
Content-Type: application/json

{
  "username": "tester",
  "password": "12345678a*",
  "nickname": "테스터",
  "email": "test@test.com",
  "contact": "010-1111-2222"
}

### 로그인
POST http://localhost:19091/api/v1/users/login
Content-Type: application/json

{
  "username": "tester",
  "password": "12345678a*"
}

> {%
    // 로그인 응답에서 access_token 값을 추출해서 `access_token` 변수에 저장
    client.global.set("access_token", response.headers.valueOf("Authorization"));
%}

### 유저 조회(개인)
GET http://localhost:19091/api/v1/users/me
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 유저 정보 수정
PUT http://localhost:19091/api/v1/users/me
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "nickname": "테스터",
  "email": "test@test.com",
  "contact": "010-1111-2212"
}

### 유저 암호 수정
PUT http://localhost:19091/api/v1/users/password
Content-Type: application/json
Authorization: BBearer {{access_token}}

{
  "currentPassword": "12345678a*",
  "newPassword": "12345678a"
}

### 유저 탈퇴 todo: 추후 feignclient grpc를 통해 수정 작업 진행
DELETE http://localhost:19091/api/v1/users/me
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "password": "12345678a"
}

### 유저 조회 username기반
GET http://localhost:19091/api/v1/users/admin/tester
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 유저 권한 상승 username기반
PUT http://localhost:19091/api/v1/users/admin/tester
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "role": "MANAGER"
}

### 유저 조회 userId기반
GET http://localhost:19091/internal/v1/users/09a6b989-86e0-4244-a120-683aef98a599
Content-Type: application/json


