spring:
  profiles:
    active: local
    include: secret
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://user-db:3309/user_db
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/
    register-with-eureka: true

jwt:
  issuer: "oneul-tanda"
  access-expiration: 30 # Access Token: min
  refresh-expiration: 7 # Refresh Token: day