spring:
  profiles:
    active: local
    include: secret
  application:
    name: user-service

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true

jwt:
  issuer: "oneul-tanda"
  access-expiration: 30 # Access Token: min
  refresh-expiration: 7 # Refresh Token: day