spring:
  profiles:
    active: local
  application:
    name: reservation-service

  datasource:
    url: jdbc:mysql://reservation-db:3307/reservation_db
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        spring.jpa.open-in-view: false
        default_batch_fetch_size: 10
        default_schema: reservation_db
        dialect: org.hibernate.dialect.MySQL8Dialect


  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer



## actuator and prometheus setting
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    health:
      show-details: always


server:
  port: 19095

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/
    register-with-eureka: true
    fetch-registry: true