### 예약 생성 요청
POST http://localhost:19095/api/v1/reservations
Content-Type: application/json

{
  "userId": 1,
  "tickets": [
    {
      "flightId": "b84b09ef-1e4f-4cb2-9121-3ad86c013551",
      "seatClass": "ECONOMY",
      "price": 120000,
      "passenger": {
        "birth": "1995-03-15",
        "gender": "MALE",
        "passportNumber": "M12345678"
      }
    },
    {
      "flightId": "a123b09c-2d4f-4cb2-9999-1fdc3e001234",
      "seatClass": "BUSINESS",
      "price": 320000,
      "passenger": {
        "birth": "1993-08-21",
        "gender": "FEMALE",
        "passportNumber": "F98765432"
      }
    }
  ]
}

