name: Deploy to aws via SSH

on:
#  workflow_run:
#    workflows:
#      - "Build and Push Docker Images"
#    types:
#      - completed
  push:
    branches:
    - Ci/#91-cicd-gitaction

jobs:
  deploy:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up .env
        run: |
          echo "JWT_SECRET_KEY=${{ env.JWT_SECRET_KEY }}" >> .env
          echo "USER_DB_ROOT_PASSWORD=${{ env.USER_DB_ROOT_PASSWORD }}" >> .env
          echo "USER_DB_ID=${{ env.USER_DB_ID }}" >> .env
          echo "USER_DB_PASSWORD=${{ env.USER_DB_PASSWORD }}" >> .env
          echo "RESERVATION_DB_ROOT_PASSWORD=${{ env.RESERVATION_DB_ROOT_PASSWORD }}" >> .env
          echo "RESERVATION_DB_ID=${{ env.RESERVATION_DB_ID }}" >> .env
          echo "RESERVATION_DB_PASSWORD=${{ env.RESERVATION_DB_PASSWORD }}" >> .env
          echo "FLIGHT_DB_ID=${{ env.FLIGHT_DB_ID }}" >> .env
          echo "FLIGHT_DB_PASSWORD=${{ env.FLIGHT_DB_PASSWORD }}" >> .env
          echo "AMADEUS_CLIENT_ID=${{ env.AMADEUS_CLIENT_ID }}" >> .env
          echo "AMADEUS_CLIENT_SECRET=${{ env.AMADEUS_CLIENT_SECRET }}" >> .env
          echo "GF_SECURITY_ADMIN_USER=${{ env.GF_SECURITY_ADMIN_USER }}" >> .env
          echo "GF_SECURITY_ADMIN_PASSWORD=${{ env.GF_SECURITY_ADMIN_PASSWORD }}" >> .env

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Make sure remote directory exists
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.INSTANCE_IP }} "mkdir -p /home/${{ secrets.SSH_USER }}/app"

      - name: Send docker-compose files and .env
        run: |
          scp ./docker-compose-server.yml ${{ secrets.SSH_USER }}@${{ secrets.INSTANCE_IP }}:/home/ubuntu/app/docker-compose.yml
          scp ./.env ${{ secrets.SSH_USER }}@${{ secrets.INSTANCE_IP }}:/home/ubuntu/app/
          scp ./prometheus.yml ${{ secrets.SSH_USER }}@${{ secrets.INSTANCE_IP }}:/home/ubuntu/app/

      - name: Run docker compose on server
        run: |
          ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.INSTANCE_IP }} "
            cd /home/${{ secrets.SSH_USER }}/app &&
            docker compose pull &&
            docker compose down &&
            docker compose up -d
          "